### ISSUE TITLE
Documentation what parquet.schema(<uri>) etc. gives back

### ISSUE THREAD

**Issue by sfkeller** [CrunchyData/pg_parquet#48]
Any documentation what "Inspect Parquet schema" like parquet.schema(<uri>) and "Inspect Parquet metadata" gives back?

**Comment by aykut-bozkurt** [comment]
I will add a sample to README.md. For now, return values are https://github.com/CrunchyData/pg_parquet/blob/main/src/parquet_udfs/schema.rs#L20
