### ISSUE TITLE
Error instaaling

### ISSUE THREAD

**Issue by HenrikPedDK** [CrunchyData/pg_parquet#66]
Hi there

I am having issues when i come to: cargo pgrx run

"develop@pggrid:~$ cargo pgrx run
Error:
   0: couldn't get cargo metadata
   1: `cargo metadata` exited with an error: error: could not find `Cargo.toml` in `/home/develop` or any parent directory
"
This is both on a Ubuntu 22.04 with PG15 and a 24.04 with PG17..

/Henrik

**Comment by marcoslot** [comment]
You need to be in the source directory, so:
```
git clone https://github.com/CrunchyData/pg_parquet.git
cd pg_parquet
cargo pgrx run
```

**Comment by HenrikPedDK** [comment]
Thank you. Got me a bit further. Now I get this:


Caused by:
  process didn't exit successfully: `/home/develop/pg_parquet/target/debug/build/pgrx-pg-sys-f18bc29725d429de/build-script-bindgen` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=PGRX_BUILD_VERBOSE
  cargo:rerun-if-env-changed=PGRX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-env-changed=PGRX_PG_CONFIG_PATH
  cargo:rerun-if-env-changed=PGRX_PG_CONFIG_AS_ENV
  cargo:rerun-if-env-changed=LLVM_CONFIG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_STATIC_PATH
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=PGRX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-changed=include
  cargo:rerun-if-changed=pgrx-cshim.c
  cargo:rerun-if-changed=/home/develop/.pgrx/config.toml
  cargo:rerun-if-env-changed=PGRX_TARGET_INFO_PATH_PG17_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_TARGET_INFO_PATH_PG17
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_PG17_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_PG17
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER

  --- stderr
  build_paths=BuildPaths { manifest_dir: "/home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.12.6", out_dir: "/home/develop/pg_parquet/target/debug/build/pgrx-pg-sys-015f724bdbcc3981/out", src_dir: "/home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.12.6/src/include", shim_src: "/home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.12.6/pgrx-cshim.c", shim_dst: "/home/develop/pg_parquet/target/debug/build/pgrx-pg-sys-015f724bdbcc3981/out/pgrx-cshim.c" }
  Generating bindings for pg17
  pg_config --configure CLANG = Some("/usr/bin/clang-17")
  Bindgen found Ubuntu clang version 18.1.3 (1ubuntu1)
  found libclang at /usr/lib/llvm-18/lib/libclang-18.so.1
  Found include dirs []
  /home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.12.6/include/pg17.h:12:10: fatal error: 'postgres.h' file not found
  Error: bindgen failed for pg17

  Caused by:
     0: Unable to generate bindings for pg17
     1: clang diagnosed error: /home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.12.6/include/pg17.h:12:10: fatal error: 'postgres.h' file not found


  Location:
      /home/develop/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-bindgen-0.12.6/src/build.rs:799:10
warning: build failed, waiting for other jobs to finish...
develop@pggrid:~/pg_parquet$

**Comment by HenrikPedDK** [comment]
Found out. Needed to install postgres dev tools :)
