### ISSUE TITLE
Add settings for shared credentials file and config

### ISSUE THREAD

**Issue by marcoslot** [CrunchyData/pg_parquet#70]
It's a bit unusual to configure PostgreSQL extensions via environment variables. It would be nice if there were GUCs corresponding to AWS_SHARED_CREDENTIALS_FILE and AWS_CONFIG_FILE.

**Comment by aykut-bozkurt** [comment]
As discussed, we decided to not introduce gucs for object store settings since it is confusing to sync the gucs and environment variables. If required, might be good to do it at a reusable place.
